name: Build ApexTunnel APK

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v4
      with:
        log-accepted-android-sdk-licenses: false
        cmdline-tools-version: '14742923'
        packages: 'platforms;android-34 build-tools;34.0.0 platform-tools'

    - name: Download libv2ray
      uses: robinraju/release-downloader@v1.10
      with:
        repository: '2dust/AndroidLibXrayLite'
        latest: true
        fileName: 'libv2ray.aar'
        out-file-path: V2rayNG/app/libs/

    - name: Build Debug APK
      run: |
        cd ${{ github.workspace }}/V2rayNG
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon

    - name: Collect and Prepare APK
      run: |
        mkdir -p ${{ github.workspace }}/apk-output
        find ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/ -name "*.apk" -exec cp {} ${{ github.workspace }}/apk-output/ \;

    - name: Upload ApexTunnel APK
      uses: actions/upload-artifact@v4
      if: ${{ success() }}
      with:
        name: ApexTunnel-Debug-APK
        path: ${{ github.workspace }}/apk-output/*.apk